---@diagnostic disable: undefined-global

option("mm_self_test")
    set_default(false)
    set_showmenu(true)
    set_description("enable early memory runtime self-test")
option_end()

option("slab_debug")
    set_default(false)
    set_showmenu(true)
    set_description("enable slab allocator debug guards")
option_end()

option("page_fault_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only page fault trigger")
option_end()

option("timer_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only timer IRQ smoke marker")
option_end()

option("ap_startup_percpu_timers")
    set_default(false)
    set_showmenu(true)
    set_description("enable bounded AP startup / per-CPU APIC timer baseline")
option_end()

option("keyboard_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only keyboard IRQ smoke handler")
option_end()

option("scheduler_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only scheduler two-thread smoke")
option_end()

option("scheduler_semantics_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only timer preemption scheduler semantics smoke")
option_end()

option("scheduler_smp_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only multi-core scheduler smoke")
option_end()

option("tlb_shootdown_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only SMP IPI / TLB shootdown smoke markers")
option_end()

option("multicore_hardening_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only multicore runtime hardening smoke")
option_end()

option("blocking_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only blocking primitive smoke")
option_end()

option("user_vmem_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only user address space vmem smoke marker")
option_end()

option("syscall_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only ring0 int 0x80 syscall self-test")
option_end()

option("user_program_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only first user program ring3 smoke")
option_end()

option("user_elf_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only filesystem-backed user ELF ring3 smoke")
option_end()

option("fs_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only kernel exFAT filesystem smoke marker")
option_end()

option("block_io_request_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only bounded block I/O request layer smoke marker")
option_end()

option("pci_config_vector_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only PCI config access and IRQ vector allocation smoke marker")
option_end()

option("pci_msix_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only PCI MSI-X interrupt delivery smoke marker")
option_end()

option("virtio_blk_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only modern virtio-blk MSI-X block driver smoke marker")
option_end()

option("virtio_net_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only modern virtio-net MSI-X tap-backed network driver smoke marker")
option_end()

option("modern_storage_backend_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only modern storage backend request/cache/writeback integration smoke marker")
option_end()

option("demand_paging_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only demand-paging lazy materialization / kill smoke marker")
option_end()

option("file_backed_mapping_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only bounded read-only file-backed mapping smoke marker")
option_end()

option("shared_readonly_mappings_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only shared read-only file-backed mapping smoke marker")
option_end()

option("anonymous_lifecycle_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only anonymous mapping unmap/protect lifecycle smoke marker")
option_end()

option("growable_tables_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only growable process/fd table smoke marker")
option_end()

option("fork_cow_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only fork/copy-on-write smoke marker")
option_end()

option("time_identity_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only wall-clock time and process identity smoke marker")
option_end()

option("signal_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only minimal signal model smoke marker")
option_end()

option("writable_fs_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only writable filesystem (bigfs) smoke marker")
option_end()

option("persistent_writable_fs")
    set_default(false)
    set_showmenu(true)
    set_description("enable persistent /rw backend on the independent ATA primary-slave test disk")
option_end()

option("persistent_writable_fs_modern_backend")
    set_default(false)
    set_showmenu(true)
    set_description("select the validation-only modern block backend for persistent /rw instead of the ATA test disk")
option_end()

option("persistent_writable_fs_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only persistent /rw two-boot smoke markers")
option_end()

option("pipe_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only pipe / dup smoke marker")
option_end()

option("userland_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only userland runtime (crt0/libc/shell) smoke marker")
option_end()

option("sleep_syscall_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only blocking sleep syscall user smoke marker")
option_end()

option("filesystem_maturity_smoke")
    set_default(false)
    set_showmenu(true)
    set_description("enable validation-only runtime filesystem maturity smoke marker")
option_end()
