name: CRLF Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  crlf-check:
    runs-on: ubuntu-latest

    steps:
      - name: check-crlf
        uses: erclu/check-crlf@v1.2.0
