on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
name: Newline ACtion

jobs:
  build:
    runs-on: ubuntu-latest
    name: Fix final line endings
    steps:
      - uses: actions/checkout@master
      - uses: Logerfo/newline-action@0.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
